---
comment: "*an introduction to functions and objects*"
output: 
  html_document:
    includes:
      in_header: resizer.html
       
runtime: shiny_prerendered
---

```{r setup, include = FALSE}
library(learnr)
library(tidyverse)
library(skimr)
library(knitr)
knitr::opts_chunk$set(error = TRUE,
  upload.fun = imgur_upload, exercise.cap = "Vectors in R")
```

```{r vector_logical, exercise=TRUE}
vector_logical <- c(TRUE, FALSE, TRUE, FALSE, FALSE)
# print 'vector_logical' below
```

```{r prepare-vector_logical-typeof, include=FALSE}
vector_logical <- c(TRUE, FALSE, TRUE, FALSE, FALSE)
```

```{r vector_logical-typeof, exercise=TRUE, exercise.setup = "prepare-vector_logical-typeof"}
# check the type of 'vector_logical' below
typeof()
```

```{r prepare-vector_logical-sum, include=FALSE}
vector_logical <- c(TRUE, FALSE, TRUE, FALSE, FALSE)
```

```{r sum-vector_logical, exercise=TRUE, exercise.setup = "prepare-vector_logical-sum"}
# check the sum of 'vector_logical' below
sum()
```

```{r concatenate, exercise=TRUE}
vector_double <- c(3, 7, 29, 4, 6.78)
# type 'vector_double' on the line below and click Run Code again
```

```{r prepare-vector_double, include=FALSE}
vector_double <- c(3, 7, 29, 4, 6.78)
```

```{r typeof, exercise=TRUE, exercise.setup = "prepare-vector_double"}
typeof()
```

```{r integer, exercise=TRUE}
vector_integer <- c(4L, 21L, 2L, 3L, 10L)
# type 'vector_integer' on the line below and click Run Code again
```

```{r prepare-vector_integer, include=FALSE}
vector_integer <- c(4L, 21L, 2L, 3L, 10L)
```

```{r typeof-integer, exercise=TRUE, exercise.setup = "prepare-vector_integer"}
typeof()
```

```{r vector_string, exercise=TRUE}
vector_string <- c("hat", "chair", "cat", "dog", "book")
# check the type of 'vector_logical' below
typeof()
```

<div data-iframe-height></div>